import React, {useMemo, useState, useEffect, useRef} from 'react';
import {DataComponent, EvidenceChart, Section, Slider, SegmentedControl, Dialog, useDataApp, useDashboardTabs} from '../../data-app-public.jsx';
import {defaults,spec,VERSION,PRODUCTION,REPORT_REFERENCE,materialBalance,dimensionReactor,thermo,rate,equilibrium,bestTemperature,optimize,simulate,fields,csv,validate,linspace} from './model.mjs';
import './ammonia.css';
import ReportView from './ReportView.jsx';
const fmt=(n,d=1)=>Number.isFinite(n)?n.toLocaleString('fr-FR',{maximumFractionDigits:d,minimumFractionDigits:d}):'—';
const pct=(n,d=1)=>fmt(n*100,d)+' %';
const colors=['#25543f','#8e7355','#73854a','#a34d36','#3c3c38','#b69144'];
const tabs=[{id:'thermo',label:'Compromis thermo-cinétique'},{id:'stages',label:'Optimisation des lits'},{id:'loop',label:'Recycle & énergie'},{id:'report',label:'Réacteur & régulation'},{id:'inputs',label:'Hypothèses & données'}];
function download(name,content,type='text/csv;charset=utf-8'){window.dispatchEvent(new CustomEvent('nh3-export',{detail:{name,content,type}}));}
function ExportPanel(){
 const [item,setItem]=useState(null),[message,setMessage]=useState('');
 useEffect(()=>{const fn=e=>{setItem(e.detail);setMessage('');};window.addEventListener('nh3-export',fn);return()=>window.removeEventListener('nh3-export',fn);},[]);
 const save=()=>{const url=URL.createObjectURL(new Blob([item.content],{type:item.type})),link=document.createElement('a');link.href=url;link.download=item.name;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);setMessage('Téléchargement demandé. Si aucun fichier ne s’ouvre, copier le contenu ci-dessous.');};
 const copy=async()=>{try{await navigator.clipboard.writeText(item.content);setMessage('Contenu copié.');}catch{setMessage('Sélectionner le contenu ci-dessous puis le copier.');}};
 return <Dialog open={!!item} onClose={()=>setItem(null)} title={item?.name||'Exporter'} expanded>{item&&<div className="nh-export"><p>{item.name} · {fmt(item.content.length/1024,1)} Ko · données de simulation</p><div className="nh-actions"><button className="nh-btn nh-primary" onClick={save}>Télécharger le fichier</button><button className="nh-btn" onClick={copy}>Copier le contenu</button></div><p className="nh-note">Le JSON conserve les hypothèses, les résultats et les limites du modèle. Les CSV sont séparés par des points-virgules et utilisent le point décimal.</p><textarea aria-label="Contenu exporté" readOnly value={item.content} rows={14}/><p role="status">{message}</p></div>}</Dialog>;
}
function Mini({label,value,unit,note}){return <div className="nh-mini"><span>{label}</span><strong>{value}<small>{unit}</small></strong><p>{note}</p></div>;}
function Block({id,title,rows=[],children,description,controls}){return <DataComponent id={id} queryId="design" kind="custom" variant="card" title={title} displayRows={rows} description={description}><div data-reviewed-rows>{controls&&<div className="nh-block-controls">{controls}</div>}{children}</div></DataComponent>;}
function Chart({id,title,rows,y,fields:fs,x='temperature',xlabel='Température (°C)',ylabel,children,type='line',height=280}){return <EvidenceChart id={id} queryId="design" title={title} variant="card" rows={rows} sourceRows={rows} height={height} spec={{type,x,y,fields:fs,stackable:false,xLabel:xlabel,yLabel:ylabel,valueDecimals:3,colors:{'Cinétique normalisée':'#73854a','Force thermodynamique':'#62615b','Vitesse nette normalisée':'#25543f'}}}>{children}</EvidenceChart>;}
function DataGrid({head,rows}){return <><p className="nh-mobile-table-hint">Faire défiler le tableau horizontalement pour voir toutes les colonnes →</p><div className="nh-table-scroll" tabIndex="0" aria-label="Tableau défilant horizontalement"><table className="nh-table"><thead><tr>{head.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table></div></>;}

function Map({r,a,probe,setProbe}){
 const [hover,setHover]=useState(null);const W=940,H=460,L=62,R=22,TOP=22,B=53,plotW=W-L-R,plotH=H-TOP-B;
 const tlo=300,thi=Math.max(a.limitT,580),xhi=Math.max(.65,r.X+.05),sx=T=>L+(T-tlo)/(thi-tlo)*plotW,sy=x=>H-B-x/xhi*plotH;
 const map=useMemo(()=>{const cells=[],ridge=[],eq=[];for(let j=0;j<45;j++){const x=(j+.5)*xhi/45,opt=bestTemperature(x,r.P,a);ridge.push({x,T:opt.T});for(let i=0;i<55;i++){const T=tlo+(i+.5)*(thi-tlo)/55,v=rate(T+273.15,r.P,x,a),rel=Math.max(0,v)/Math.max(opt.r,1e-12);cells.push({i,j,x,T,rate:v,rel});}}for(let T=tlo;T<=thi;T+=3)eq.push({T,x:equilibrium(T+273.15,r.P)});return {cells,ridge,eq};},[r.P,a.r0,a.ea,a.activity,a.limitT,xhi,thi]);
 const path=pts=>pts.map((p,i)=>(i?'L':'M')+sx(p.T).toFixed(1)+','+sy(p.x).toFixed(1)).join(' ');
 const hit=e=>{const b=e.currentTarget.getBoundingClientRect(),px=(e.clientX-b.left)*W/b.width,py=(e.clientY-b.top)*H/b.height,T=tlo+(px-L)/plotW*(thi-tlo),x=(H-B-py)/plotH*xhi;if(T>=tlo&&T<=thi&&x>=0&&x<=xhi)setHover({T,x,r:rate(T+273.15,r.P,x,a)});};
 const opt=bestTemperature(probe,r.P,a),active=hover||{T:opt.T,x:probe,r:opt.r};
 return <div className="nh-map"><svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Carte température-conversion : vitesse relative, équilibre et lits adiabatiques. Flèches haut et bas : conversion de la coupe." tabIndex="0" onKeyDown={e=>{if(['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();setProbe(Math.max(.02,Math.min(.6,probe+(e.key==='ArrowUp'?.01:-.01))));}}} onPointerMove={hit} onPointerLeave={()=>setHover(null)} onClick={()=>hover&&setProbe(Math.max(.02,Math.min(.6,hover.x)))}>
  <defs><clipPath id="nh-plot-clip"><rect x={L} y={TOP} width={plotW} height={plotH}/></clipPath><pattern id="nh-over-limit" width="8" height="8" patternUnits="userSpaceOnUse"><path d="M0 8 L8 0" stroke="#9a6e56" strokeWidth="1" opacity="0.45"/></pattern></defs><g clipPath="url(#nh-plot-clip)">
  {map.cells.map(c=><rect key={c.i+'-'+c.j} x={L+c.i*plotW/55} y={H-B-(c.j+1)*plotH/45} width={plotW/55+.3} height={plotH/45+.3} fill={c.rate<=0?'#e8e8e4':c.rel>=.95?'#9ab493':`hsl(125 16% ${97-Math.pow(Math.min(c.rel,1),.5)*36}%)`}/>)}
  {linspace(0,xhi,6).map(x=><line key={x} x1={L} x2={W-R} y1={sy(x)} y2={sy(x)} stroke="#d5dcd7" strokeDasharray="3 5"/>)}
  <rect x={sx(a.limitT)} y={TOP} width={Math.max(0,sx(thi)-sx(a.limitT))} height={plotH} fill="url(#nh-over-limit)"/><line x1={sx(a.limitT)} x2={sx(a.limitT)} y1={TOP} y2={H-B} stroke="#9a6e56" strokeDasharray="4 4"/><path d={path(map.eq)} stroke="#777f80" strokeWidth="2" fill="none" strokeDasharray="6 5"/><path d={path(map.ridge)} stroke="#25543f" strokeWidth="2.6" fill="none"/>
  {r.beds.map((bed,i)=><g key={bed.lit}><path d={path(r.points.filter(p=>p.lit===bed.lit).map(p=>({T:p.T,x:p.X})))} fill="none" stroke={colors[i]} strokeWidth="4"/>{i<r.N-1&&<line x1={sx(bed.Tout)} x2={sx(r.beds[i+1].Tin)} y1={sy(bed.Xout)} y2={sy(bed.Xout)} stroke={colors[i]} strokeWidth="2" strokeDasharray="5 4"/>}<circle cx={sx(bed.Tout)} cy={sy(bed.Xout)} r="5" fill={colors[i]} stroke="white" strokeWidth="2"/><text x={sx(bed.Tout)+9} y={sy(bed.Xout)-9} className="nh-bed-label">L{bed.lit}</text></g>)}
  <line x1={L} x2={W-R} y1={sy(probe)} y2={sy(probe)} stroke="#7c705b" strokeWidth="1.4" strokeDasharray="3 4"/>{hover&&<circle cx={sx(hover.T)} cy={sy(hover.x)} r="5" fill="white" stroke="#253c2d" strokeWidth="2"/>}</g>
  {[300,350,400,450,500,550,600,650].filter(T=>T<=thi).map(T=><text key={T} x={sx(T)} y={H-B+23} textAnchor="middle">{T}</text>)}{linspace(0,xhi,6).map(x=><text key={x} x={L-12} y={sy(x)+4} textAnchor="end">{fmt(x*100,0)} %</text>)}<text x={L+plotW/2} y={H-8} textAnchor="middle">Température (°C)</text><text transform={`translate(15 ${TOP+plotH/2}) rotate(-90)`} textAnchor="middle">Conversion N₂ par passage</text>
 </svg><div className="nh-map-readout" aria-live="polite"><span><b>{fmt(active.T,0)} °C</b> · X = {pct(active.x)}</span><span>r<sub>N₂</sub> = <b>{fmt(active.r,4)}</b> kmol/(kg·h)</span></div><div className="nh-legend"><span><i style={{background:'#25543f'}}/>T° de vitesse maximale à X fixé</span><span><i style={{background:'#9ab493'}}/>Bande ≥ 95 % du maximum local</span><span><i style={{background:'#25543f'}}/>Trajectoires adiabatiques</span><span><i style={{background:'#e0e2df'}}/>Réaction inverse favorisée</span></div><p className="nh-note">Carte à {fmt(r.P,1)} bar ; chaque lit utilise sa pression propre. Zone hachurée : au-delà du plafond de {a.limitT} °C. Les segments pointillés entre lits représentent le refroidissement à conversion constante. Cliquer dans la carte change la coupe ci-dessous.</p></div>;
}

function ThermoView({r,a,update}){
 const probe=a.probeX,optimal=bestTemperature(probe,r.P,a);
 const curve=useMemo(()=>{const temps=linspace(300,a.limitT,90),rates=temps.map(T=>rate(T+273.15,r.P,probe,a)),peak=Math.max(...rates,1e-10);return temps.map((T,i)=>{const t=T+273.15,n=(1-probe)/(4-2*probe),h=3*n,z=2*probe/(4-2*probe),q=z*z/(n*h**3*r.P*r.P);return {temperature:T,'Cinétique normalisée':Math.exp(-a.ea*1000/8.314462618*(1/t-1/(a.limitT+273.15))),'Force thermodynamique':Math.max(0,1-q/thermo(t).K),'Vitesse nette normalisée':Math.max(0,rates[i])/peak,vitesse_N2:rates[i]};});},[probe,r.P,a.ea,a.r0,a.activity,a.limitT]);
 return <><Section id="nh-thermo-title" title="Où refroidir pour relancer la réaction ?" spacing="content"><Block id="nh-operating-map" title="Température × conversion" rows={r.points} description="Couleur normalisée séparément à chaque conversion ; ce n’est pas une carte de vitesse absolue. Équilibre idéal et trajectoire calculée avec cinétique de substitution."><Map r={r} a={a} probe={probe} setProbe={v=>update('probeX',v)}/></Block></Section>
  <Section id="nh-cross-title" title="Le compromis à composition fixée" columns={2}>
   <Chart id="nh-cross" title="Cinétique, force motrice et vitesse nette" rows={curve} y="Vitesse nette normalisée" fields={['Cinétique normalisée','Force thermodynamique','Vitesse nette normalisée']} ylabel="Indice normalisé (0–1)"><p className="nh-note">Les indices sont normalisés séparément. Leur intersection dépend de l’échelle : le critère physique est le maximum de la vitesse nette. La force et la vitesse négatives sont ramenées à zéro sur cette coupe.</p></Chart>
   <Block id="nh-cross-choice" title="Une coupe dans le domaine" rows={[{X:probe,P:r.P,Topt:optimal.T,rmax:optimal.r}]}><Slider label="Conversion fixée pour la coupe" value={probe} min={.02} max={.6} step={.01} onChange={v=>update('probeX',v)} formatValue={v=>pct(v)} showBounds/><div className="nh-optimum"><span>Maximum local de vitesse</span><strong>{fmt(optimal.T,0)} <small>°C</small></strong><p>à X = {pct(probe)} et P = {fmt(r.P,1)} bar</p></div><p className="nh-note">À basse température, la réaction est lente. À haute température, la force motrice s’effondre à l’approche de l’équilibre. Le catalyseur accélère la réaction, sans déplacer l’équilibre.</p><div className="nh-formula">r = facteur cinétique × (1 − Q / K)</div></Block>
  </Section><Section id="nh-cooling-title" title="Détection du refroidissement par lit"><Block id="nh-cooling-table" title="Maximum de vitesse et sortie retenue" rows={r.beds}><DataGrid head={['Lit','Pic de vitesse','X au pic','Sortie retenue','X en sortie','Critère d’arrêt','Seuil r / pic']} rows={r.beds.map(b=>[b.lit,fmt(b.peakT,1)+' °C',pct(b.peakX),fmt(b.Tout,1)+' °C',pct(b.Xout),b.stop,pct(b.threshold,0)])}/><p className="nh-note">Le pic de vitesse sur l’adiabatique et le point de refroidissement sont distincts. La recherche économique ajuste la température d’entrée et le seuil de vitesse de chaque lit ; elle respecte aussi les plafonds de température et de catalyseur.</p></Block></Section></>;
}

function StagesView({results,r,a,choose}){
 const winners=results.winners||[],best=results.best,nearby=best?results.rows.filter(w=>w.cost<=best.cost*1.05):[];
 const atEdge=best&&(Math.abs(best.P-a.pMin)<.1||Math.abs(best.P-a.pMax)<.1||best.N===a.maxBeds||best.beds.some(b=>Math.abs(b.Tin-a.tMin)<.1||Math.abs(b.Tin-a.tMax)<.1));
 return <><div className="nh-callout"><b>{best?`${best.N} lits : meilleur candidat du modèle`:'Aucun candidat admissible'}</b><p>{best?`Minimum trouvé : ${fmt(best.cost,0)} MAD/t, à ${fmt(best.P,1)} bar. ${results.count.toLocaleString('fr-FR')} configurations admissibles sur ${results.tried.toLocaleString('fr-FR')}, puis affinage local des températures et des seuils par lit.`:'Élargir les limites ou revoir les hypothèses.'} {atEdge?'Au moins une variable atteint une borne : le domaine doit être réexaminé.':''}</p></div>
  <Section id="nh-config-title" title="Même production, configurations réoptimisées" columns={2} spacing="content"><Chart id="nh-cost-chart" title="Coût partiel de synthèse" rows={winners.map(w=>({lits:w.N,'Coût partiel':w.cost}))} x="lits" y="Coût partiel" xlabel="Nombre de lits" ylabel="MAD / t NH₃" type="bar"/><Chart id="nh-conversion-chart" title="Conversion par passage" rows={winners.map(w=>({lits:w.N,'Conversion (%)':w.X*100}))} x="lits" y="Conversion (%)" xlabel="Nombre de lits" ylabel="% du N₂ entrant"/></Section>
  <Section id="nh-candidates-title" title="Choisir un candidat pour l’explorer"><Block id="nh-candidates" title="Comparaison des configurations" rows={winners.map(fields)} controls={<button className="nh-btn" onClick={()=>download('nh3-configurations.csv',csv(winners.map(fields)))}>Exporter la comparaison CSV</button>}><DataGrid head={['Configuration','P (bar)','T entrées (°C)','X passage','ΔX (points)','Catalyseur (t)','R / F','MAD/t','ΔTAC (MMAD/an)','']} rows={winners.map((w,i)=>[<b>{w.N} {w.N===1?'lit':'lits'}{w.N===best?.N?' ★':''}</b>,fmt(w.P),w.beds.map(b=>fmt(b.Tin,0)).join(' / '),pct(w.X),i?fmt((w.X-winners[i-1].X)*100,2):'—',fmt(w.mass/1000),fmt(w.recycleRatio,2),fmt(w.cost,0),i?fmt((w.tac-winners[i-1].tac)/1e6,2):'—',<button className={'nh-btn '+(r.N===w.N?'nh-active':'')} onClick={()=>choose(w.N)}>Explorer</button>])}/><p className="nh-note">ΔX compare des configurations réoptimisées ; il peut être négatif. ΔTAC &lt; 0 signifie que l’ajout du lit diminue le coût annuel partiel. Le minimum est choisi sur l’ensemble des configurations, sans règle d’arrêt au premier gain négatif.</p></Block></Section>
  <Section id="nh-catalyst-title" title={`Répartition calculée · ${r.N} lits`} columns={2}><Chart id="nh-catalyst" title="Catalyseur par lit" rows={r.beds.map(b=>({lit:b.lit,'Masse (t)':b.mass/1000}))} x="lit" y="Masse (t)" xlabel="Lit" ylabel="Tonnes de catalyseur" type="bar"/><Block id="nh-search-domain" title="Ce que signifie « optimum »" rows={[{candidates:results.count,nearby:nearby.length}]}><div className="nh-formula">min TAC / 100 000 t<br/><small>sous contraintes de production et de température</small></div><p>La grille explore 7 pressions, 5 températures d’entrée, 3 profils de refroidissement et 5 seuils de vitesse, pour chaque nombre de lits. Un affinage local ajuste ensuite chaque température et chaque seuil séparément.</p><p>La masse de catalyseur provient de l’intégrale ∫ F<sub>N₂,0</sub> / r dX. Elle n’est pas fixée à l’avance.</p><p className="nh-note">{nearby.length} points de grille sont à moins de 5 % du coût du meilleur candidat affiné. Cette bande mesure la sensibilité au choix de configuration, pas une incertitude statistique. La recherche reste discrète et locale ; l’optimum global n’est pas démontré.</p></Block></Section><Sensitivity a={a} baseline={best}/></>;
}

function Sensitivity({a,baseline}){
 const [rows,setRows]=useState([]),[running,setRunning]=useState(false),[done,setDone]=useState(0),generation=useRef(0);
 const key=spec.map(([k])=>a[k]).join('|');
 useEffect(()=>{generation.current++;setRows([]);setRunning(false);setDone(0);return()=>{generation.current++;};},[key]);
 const definitions=spec;
 const scenarioCount=definitions.length*2;
 const scenarioValue=(def,base,side)=>{const [, , ,min,max,step]=def,raw=side<0?base-.25*(base-min):base+.25*(max-base);let value=Math.max(min,Math.min(max,raw));if(step>=1)value=Math.round(value/step)*step;return Number(value.toFixed(8));};
 const run=async()=>{
  const job=++generation.current;setRunning(true);setRows([]);setDone(0);const out=[];
  for(const def of definitions)for(const side of [-1,1]){
   await new Promise(resolve=>setTimeout(resolve,0));if(job!==generation.current)return;
   const parameter=def[0],value=scenarioValue(def,a[parameter],side),result=optimize({...a,[parameter]:value}),best=result.best;
   out.push({hypothese:def[1],parametre:parameter,cas:side<0?'Basse':'Haute',valeur:value,unite:def[2],lits:best?.N??null,pression_bar:best?.P??null,conversion:best?.X??null,cout_partiel_MAD_t:best?.cost??null,variation_cout_pct:best&&baseline?(best.cost/baseline.cost-1)*100:null,classification:'sensibilité une hypothèse à la fois; modèle non calibré'});
   if(job!==generation.current)return;setDone(out.length);
  }
  setRows(out);setRunning(false);
 };
 const changed=rows.filter(row=>row.lits!==baseline?.N).length;
 return <Section id="nh-sensitivity-title" title="Le résultat dépend-il des hypothèses ?"><Block id="nh-sensitivity" title="Sensibilité du meilleur candidat" rows={rows} controls={<><button className="nh-btn nh-primary" disabled={running} onClick={run}>{running?`Calcul ${done} / ${scenarioCount}…`:`Évaluer ${scenarioCount} scénarios`}</button>{rows.length>0&&<button className="nh-btn" onClick={()=>download('nh3-sensibilite.json',JSON.stringify({version:VERSION,production_t_an:PRODUCTION,base_assumptions:a,baseline:baseline?fields(baseline):null,scenarios:rows},null,2),'application/json')}>Exporter la sensibilité</button>}</>}><p className="nh-note">Tous les paramètres numériques du cahier des charges sont diminués puis augmentés de 25 %, dans leurs limites admissibles. Chaque scénario réoptimise les lits, la pression, les températures et les seuils ; toutes les autres hypothèses restent identiques. Il s’agit d’une sensibilité isolée, sans probabilité ni intervalle de confiance.</p>{rows.length>0?<><p><b>{changed} scénario(s) sur {scenarioCount} changent le nombre de lits retenu.</b> Les conclusions restent conditionnelles à la cinétique, aux coûts partiels et au domaine exploré.</p><DataGrid head={['Hypothèse','Cas','Valeur','Lits','P (bar)','X passage','MAD/t','Δ coût']} rows={rows.map(row=>[row.hypothese,row.cas,fmt(row.valeur,2)+' '+row.unite,row.lits,fmt(row.pression_bar),pct(row.conversion),fmt(row.cout_partiel_MAD_t,0),fmt(row.variation_cout_pct,1)+' %'])}/></>:<p>{running?'Recalcul des configurations en cours…':'Lancer l’analyse pour comparer tous les paramètres numériques et identifier les hypothèses qui changent le choix de conception.'}</p>}</Block></Section>;
}

function LoopView({r,a}){
 const balance=materialBalance(r),annualRows=['fresh','recycle','reactor','purge'].flatMap((stream)=>['N2','H2'].map(species=>({flux:({fresh:'Gaz frais',recycle:'Recycle',reactor:'Entrée réacteur',purge:'Purge'})[stream],espece:species,...balance[stream][species]})));
 const electricLoad=r.freshMW+r.recycleMW+r.coolingMW;
 const flows=[['NH₃ produit',r.fNH3,PRODUCTION/a.hours],['N₂ frais',r.freshN,r.freshN*28.0134/1000],['H₂ frais',3*r.freshN,3*r.freshN*2.01588/1000],['Gaz à l’entrée du réacteur',4*r.reactN,r.reactN*(28.0134+3*2.01588)/1000],['Recycle H₂ + N₂',4*r.recycleN,r.recycleN*(28.0134+3*2.01588)/1000],['Purge H₂ + N₂',4*r.purgeN,r.purgeN*(28.0134+3*2.01588)/1000]];
 const costs=[{poste:'Capital annualisé',MAD:r.annualCapital/1e6},{poste:'Maintenance',MAD:r.annualMaintenance/1e6},{poste:'Renouvellement catalyseur',MAD:r.annualCat/1e6},{poste:'Électricité nette',MAD:r.annualEnergy/1e6},{poste:'Gaz frais N₂ + H₂',MAD:r.annualFeed/1e6}];
 return <><Section id="nh-flows-title" title="De l’H₂ et du N₂ purifiés au NH₃ séparé" spacing="content"><Block id="nh-process" title="Boucle de synthèse simplifiée" rows={flows.map(([flux,kmol_h,t_h])=>({flux,kmol_h,t_h}))}><div className="nh-flow"><div>H₂ / N₂ frais<small>{fmt(4*r.freshN,0)} kmol/h</small></div><span>→</span><div>Compression & mélange<small>{fmt(r.P,1)} bar</small></div><span>→</span><div className="nh-flow-reactor">{r.N} {r.N===1?'lit':'lits + échangeurs'}<small>X = {pct(r.X)}</small></div><span>→</span><div>Refroidissement & séparation<small>NH₃ → stockage</small></div></div><div className="nh-return">↶ Recycle : {fmt(4*r.recycleN,0)} kmol/h · purge : {fmt(4*r.purgeN,0)} kmol/h · retour vers le mélangeur</div><p className="nh-note">Amont : dessalement → déionisation → électrolyse pour H₂ ; traitement d’air → séparation cryogénique pour N₂. Séparation complète de NH₃ et absence d’inertes : hypothèses à remplacer lors de la conception détaillée.</p></Block></Section>
  <Section id="nh-material-title" title="Bilan matière et charge de recycle" columns={2}><Block id="nh-flows" title="Débits au point sélectionné" rows={flows.map(([flux,kmol_h,t_h])=>({flux,kmol_h,t_h}))}><DataGrid head={['Flux','kmol/h','t/h','t/an']} rows={flows.map(([f,n,m])=>[f,fmt(n,1),fmt(m,4),fmt(m*a.hours,2)])}/><p className="nh-note">Les tonnages de recycle et d’entrée réacteur comptent plusieurs passages ; seuls les gaz frais constituent le besoin à demander aux équipes amont.</p></Block><Block id="nh-recycle" title="Passage unique ≠ conversion globale" rows={[{X:r.X,globalX:r.globalX,recycleRatio:r.recycleRatio}]}><div className="nh-pair"><Mini label="Par passage" value={pct(r.X)} note="N₂ consommé / N₂ à l’entrée du réacteur"/><Mini label="Globale" value={pct(r.globalX)} note="N₂ consommé / N₂ frais"/></div><div className="nh-formula">R / F = (1 − p)(1 − X) / [X + p(1 − X)]</div><p className="nh-note">Sans purge, R/F = (1−X)/X et la conversion globale idéale vaut 100 %. La purge augmente le besoin de gaz frais. Les inertes et le NH₃ résiduel ne sont pas modélisés.</p></Block></Section>
  <Section id="nh-annual-title" title="Bilan annuel N₂ / H₂ et équations"><Block id="nh-annual-balance" title="Débits frais, recyclés et bruts par espèce" rows={annualRows} controls={<button className="nh-btn" onClick={()=>download('nh3-bilan-matiere.csv',csv(annualRows.map(row=>({modele:VERSION,heures_an:a.hours,conversion_N2:r.X,purge:a.purge,...row}))))}>Exporter le bilan CSV</button>}><DataGrid head={['Flux','Espèce','t/an','t/h','kmol/h']} rows={annualRows.map(row=>[row.flux,row.espece,fmt(row.t_an,2),fmt(row.t_h,4),fmt(row.kmol_h,3)])}/><div className="nh-formula">H = (365 − 3 × 7) × 24 = 8 256 h/an (référence)<br/>ṁNH₃ = 100 000 / H = {fmt(PRODUCTION/a.hours,4)} t/h aux hypothèses actives<br/>B<sub>N₂</sub> = 100 000 × 28,0134 / (2 × 17,03052) = 82 244,70 t/an<br/>B<sub>H₂</sub> = 100 000 × (3 × 2,01588) / (2 × 17,03052) = 17 755,30 t/an<br/>Aᵢ = Bᵢ / X ; Rᵢ = (1 − p)(1 − X) Aᵢ<br/>Fᵢ = Aᵢ − Rᵢ = Bᵢ [1 + p(1 − X)/X]<br/>Purgeᵢ = p(1 − X) Aᵢ ; ṁᵢ = mᵢ,annuel / H</div><p className="nh-note">B : consommation par réaction ; A : entrée totale ; R : recycle ; F : apport frais, en t/an. X = {pct(r.X,2)}, p = {pct(a.purge,2)}. Séparation NH₃ parfaite, pas d’inertes, de pertes ou de consommation de démarrage. À purge nulle, les besoins frais annuels ne dépendent pas de X.</p></Block></Section>
  <Section id="nh-energy-title" title="Chaleur libérée et électricité" columns={2}><Block id="nh-energy-budget" title="Budget énergétique du modèle" rows={[{chaleur_MW:r.rxnMW,recuperation_MW:r.recoveredMW,electricite_brute_MW:r.grossMW,compression_frais_MW:r.freshMW,compression_recycle_MW:r.recycleMW,auxiliaires_MW:r.coolingMW,net_achete_MW:r.netMW}]}><DataGrid head={['Grandeur','Valeur','Unité']} rows={[
 ['Chaleur chimique, référence gaz à 25 °C',fmt(r.rxnMW,3),'MWth'],['Chaleur valorisée (hypothèse)',fmt(r.recoveredMW,3),'MWth'],['Électricité brute potentielle',fmt(r.grossMW,3),'MWe'],['Compression des gaz frais',fmt(r.freshMW,3),'MWe'],['Circulateur du recycle',fmt(r.recycleMW,3),'MWe'],['Réfrigération + auxiliaires',fmt(r.coolingMW,3),'MWe'],['Total des charges',fmt(electricLoad,3),'MWe'],[<b>Électricité nette achetée dans ce périmètre</b>,<b>{fmt(r.netMW,3)}</b>,'MWe'],['Couverture par récupération',fmt(100*r.grossMW/electricLoad,1),'%']]}/><p className="nh-note">P<sub>brute</sub> = Q<sub>chimique</sub> × récupération × rendement électrique. Un achat net négatif correspond à un export théorique. Électrolyse et séparation d’air hors périmètre.</p></Block>
  <Block id="nh-cooling-method" title="Refroidissement indirect et valorisation" rows={r.beds.map(b=>({lit:b.lit,duty_MW:b.coolMW}))}><p>Le gaz chaud traverse un échangeur sans mélange avec le fluide froid. La chaleur peut préchauffer le gaz entrant ou produire de la vapeur. Une turbine et un alternateur convertiraient une partie de cette vapeur en électricité.</p><div className="nh-formula">Échangeur → vapeur → turbine → alternateur</div><p>Charge inter-lit calculée : <b>{fmt(r.qInterMW,2)} MW</b>. Elle inclut la chaleur sensible du gaz ; on ne l’ajoute pas à la chaleur de réaction pour calculer l’électricité.</p><p className="nh-note">La fraction valorisée est une hypothèse, sans réseau vapeur, pincement thermique ni turbine dimensionnés. Le CAPEX vapeur/turbine et le bilan de condensation complet manquent : l’électricité affichée n’est pas une production garantie.</p><details><summary>Autres solutions à comparer</summary><p>Quench : modifie débits et compositions. Refroidissement par air/eau : dépend des utilités et du niveau thermique. Double enveloppe : transfert à vérifier à l’échelle industrielle. Flash : séparation à traiter avec un équilibre vapeur–liquide, pas un remplacement direct du refroidissement inter-lit.</p></details></Block></Section>
  <Section id="nh-cost-title" title="Coût annuel partiel de synthèse" columns={2}><Chart id="nh-cost-split" title="Décomposition des coûts" rows={costs} x="poste" y="MAD" xlabel="Millions de MAD/an" ylabel="Millions de MAD/an" type="horizontalBar"/><Block id="nh-cost-perimeter" title="Périmètre économique" rows={[{CAPEX_MAD:r.capex,TAC_MAD_an:r.tac,cost_MAD_t:r.cost,gas_feed_MAD_an:r.annualFeed}]}><div className="nh-pair"><Mini label="CAPEX modélisé" value={fmt(r.capex/1e6,1)} unit="MMAD"/><Mini label="Coût partiel" value={fmt(r.cost,0)} unit="MAD/t"/></div><p>Inclus : réacteur, internes, échangeurs inter-lits, compression, catalyseur, maintenance, électricité nette et, si renseignés, les coûts des gaz frais N₂/H₂.</p><p className="nh-note">Les prix N₂/H₂ sont optionnels et valent zéro par défaut ; renseigner les devis dans « Hypothèses & données » pour faire entrer la purge dans le TAC. Restent exclus : stockage, réseau vapeur et turbine, génie civil, contingences et dimensionnement détaillé. Aucun prix de vente NH₃ n’est nécessaire pour comparer des coûts à production identique. Le coût total et la rentabilité du projet ne sont pas encore calculables.</p></Block></Section></>;
}
const sourceLinks=[{title:'NIST · NH₃',url:'https://webbook.nist.gov/cgi/cbook.cgi?ID=C7664417&Mask=1'},{title:'NIST · N₂',url:'https://webbook.nist.gov/cgi/cbook.cgi?ID=C7727379&Mask=1'},{title:'NIST · H₂',url:'https://webbook.nist.gov/cgi/cbook.cgi?ID=C1333740&Mask=1'},{title:'ASME · BPVC VIII-1',url:'https://www.asme.org/codes-standards/find-codes-standards/bpvc-viii-1-bpvc-section-viii-rules-construction-pressure-vessels-division-1'},{title:'API · RP 941',url:'https://www.api.org/products-and-services/standards/industry-alert'}];
const missing=[['Catalyseur : loi de vitesse, activité, vieillissement, granulométrie','Conversion, masse, perte de charge et température admissible','Fournisseur / essais'],['Fugacités, gaz réels, équilibre liquide–vapeur NH₃','Équilibre haute pression et séparation','Équation d’état validée'],['Puretés H₂/N₂ et inertes','Purge, composition et pertes de gaz frais','Électrolyse / séparation d’air'],['Disponibilité annuelle et variation de la production amont','Débit horaire, stockage tampon et charge partielle','Données d’exploitation'],['Devis et corrélations de coût datées en MAD','Coût total et classement robuste','Fournisseurs / ingénierie'],['Pression des gaz frais, compresseurs et pertes de charge','Puissance et dimensions des équipements','Fournisseurs / hydraulique'],['Utilités, vapeur, échangeurs et turbine','Récupération réelle et électricité nette','Intégration énergétique'],['Validation fournisseur et calcul mécanique ASME','Confirmer diamètre, hauteur, épaisseur, matériau, buses et supports proposés','Étude mécanique détaillée'],['Capteurs, actionneurs, maintenance et données transitoires','Régulation et futur jumeau numérique','P&ID / données terrain']];
function InputsView({a,update,results,r,reset}){
 const [notice,setNotice]=useState('');const groups=[...new Set(spec.map(s=>s[6]))];
 const exportJson=()=>download('nh3-etude.json',JSON.stringify({version:VERSION,classification:'simulation non calibrée; dimensionnement mécanique préliminaire non certifié',fixed:{production_t_an:PRODUCTION},assumptions:Object.fromEntries(Object.keys(defaults).map(k=>[k,a[k]])),selected:r?fields(r):null,material_balance:r?materialBalance(r):null,reactor_preliminary_dimensions:r?dimensionReactor(r):null,report_reference:{document:'Synthese_ammoniac_100000_t_an_8256h_style_vert.pdf',date:'2026-09-27',hours:8256,config:REPORT_REFERENCE,historical_cost_MAD_t_at_8000h:348.24},stages:r?.beds,trajectory:r?.points,comparison:results.winners?.map(fields),limitations:['Gaz idéaux','Cinétique de substitution','Coûts hypothétiques','Séparation complète NH3','Dimensions mécaniques non certifiées','CAPEX vapeur et turbine exclu','Optimum discret et local'],sources:sourceLinks},null,2),'application/json');
 const importJson=async(e)=>{try{if(!e.target.files?.length)return;const doc=JSON.parse(await e.target.files[0].text());if(![VERSION,'NH3-screening-1.1','NH3-screening-1.0'].includes(doc.version)||doc.fixed?.production_t_an!==PRODUCTION)throw Error('Format ou objectif de production incompatible.');const b={...defaults,...doc.assumptions},errors=validate(b);if(errors.length)throw Error(errors.join(' '));for(const k of Object.keys(defaults))if(!Number.isFinite(b[k]))throw Error('Paramètre invalide : '+k);update(null,Object.fromEntries(Object.keys(defaults).map(k=>[k,b[k]])));setNotice('Hypothèses importées ; calculs mis à jour.');}catch(err){setNotice('Import refusé : '+err.message);}e.target.value='';};
 return <><div className="nh-callout"><b>Une seule exigence imposée : 100 000 t NH₃/an</b><p>La référence du rapport adopte trois semaines d’arrêt : (365 − 21) × 24 = 8 256 h/an. Les heures restent modifiables pour les scénarios et déterminent le débit horaire. La disponibilité, les prix, les performances du catalyseur et les contraintes mécaniques nécessitent des données externes : ils ne peuvent pas être déduits de la seule production annuelle.</p></div><div className="nh-actions"><button className="nh-btn nh-primary" onClick={exportJson}>Exporter l’étude JSON</button><button className="nh-btn" disabled={!r} onClick={()=>download('nh3-trajectoire.csv',csv(r.points.map(p=>({modele:VERSION,classification:'simulation non calibrée',lit:p.lit,conversion_N2:p.X,temperature_C:p.T,pression_bar:p.P,vitesse_kmolN2_kgcat_h:p.r,catalyseur_cumule_kg:p.u*r.reactN,force_thermodynamique:p.force}))))}>Trajectoire CSV</button><button className="nh-btn" onClick={()=>download('nh3-grille.csv',csv(results.rows.map(fields)))}>Toute la grille CSV</button><label className="nh-btn">Importer les hypothèses<input type="file" accept=".json,application/json" onChange={importJson}/></label><button className="nh-btn" onClick={reset}>Réinitialiser les hypothèses</button></div><p role="status" className="nh-note">{notice}</p>
  <Section id="nh-input-title" title="Hypothèses modifiables"><div className="nh-input-groups">{groups.map(group=><details className="nh-input-group" key={group} open={group==='Domaine exploré'}><summary>{group}<span>{spec.filter(s=>s[6]===group).length} paramètres</span></summary><div className="nh-input-grid">{spec.filter(s=>s[6]===group).map(([key,label,unit,min,max,step])=><label className="nh-input" key={key}><span>{label}</span><div><input aria-label={label} type="number" min={min} max={max} step={step} value={Number.isFinite(a[key])?a[key]:''} onChange={e=>update(key,e.target.value===''?NaN:Number(e.target.value))}/><small>{unit}</small></div></label>)}</div></details>)}</div></Section>
  <Section id="nh-required-title" title="Données à récupérer pour une conception défendable"><Block id="nh-missing-data" title="Passer de l’exploration au dimensionnement" rows={missing.map(([donnee,pourquoi,source])=>({donnee,pourquoi,source}))}><DataGrid head={['Donnée à obtenir','Ce qu’elle détermine','Origine']} rows={missing}/></Block></Section>
  <Section id="nh-method-title" title="Équations, hypothèses structurelles et sources"><Block id="nh-methods" title="Modèle reproductible" rows={[{model:VERSION}]}><details open><summary>Thermodynamique et cinétique</summary><div className="nh-formula">N₂ + 3 H₂ ⇌ 2 NH₃<br/>K = exp(−ΔG° / RT) ; Q = a²NH₃ / (aN₂ · a³H₂)<br/>aᵢ = yᵢ P / 1 bar<br/>rN₂ = r₀ α exp[−Ea/R (1/T − 1/700)]<br/>× (aN₂/37,5)½ (aH₂/112,5)³ᐟ² × (1 − Q/K)<br/>dT/dX = −ΔHr / [(1−X)(Cp,N₂ + 3Cp,H₂) + 2X Cp,NH₃]</div><p>Cp, H° et S° proviennent des polynômes de Shomate du NIST. r₀ et Ea sont hypothétiques ; cette loi réversible de substitution n’est pas un modèle Temkin–Pyzhev validé. Le mélange stœchiométrique pur et la séparation NH₃ parfaite sont des choix structurels. Les pertes de pression sont appliquées en sortie de chaque équipement, sans équation d’Ergun.</p></details><details><summary>Énergie, coût et intégration numérique</summary><p>Pas en conversion : 0,0025 pour la grille, 0,0005 pour l’affinage. Point milieu pour la température, trapèzes pour W/F. Arrêt des lits au seuil r/rpic, à Tmax, à W/F maximal ou à proximité de l’équilibre.</p><div className="nh-formula">Puissance compresseur = F RT ln(P₂/P₁) / η<br/>TAC = CAPEX × CRF + maintenance + renouvellement catalyseur + électricité nette + gaz frais N₂/H₂</div><p>Coûts hypothétiques : réacteur ∝ (V/20 m³)^0,6 (P/150 bar)^1,2 ; échangeurs ∝ Q^0,65 ; compression ∝ puissance^0,7. Renouvellement du catalyseur annualisé séparément de la charge initiale. Les coûts de N₂ et H₂ sont optionnels et fixés à zéro tant qu’aucun devis n’est fourni.</p><p>La purge reste une variable de scénario et de sensibilité, pas une variable optimisée. Si des prix N₂/H₂ sont renseignés, sa consommation de gaz frais entre automatiquement dans le TAC. Il en va de même des heures de fonctionnement et des rendements : les optimiser librement créerait un résultat artificiel.</p></details><div className="nh-source-links">{sourceLinks.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer">{s.title} ↗</a>)}</div><p className="nh-note">Rapport utilisateur du 27 septembre 2026 intégré le 29 septembre 2026 ; sources NIST consultées le 23 septembre 2026. Le NIST justifie les propriétés thermodynamiques, pas la cinétique, les coûts ni la précision à haute pression.</p></Block></Section></>;
}

export default function AmmoniaApp(){
 const {assumptions,setAssumptions}=useDataApp(),{activeTabId}=useDashboardTabs(tabs),a={...defaults,...assumptions};
 const update=(key,value)=>setAssumptions(old=>key===null?{...old,...value}:{...old,[key]:value});
 const mode=a.resultMode===1?'manual':a.resultMode===2?'report':'optimum',selectedN=a.selectedN||0,computeKey=spec.map(([k])=>a[k]).join('|');
 const setMode=v=>update('resultMode',v==='manual'?1:v==='report'?2:0),setSelectedN=v=>update('selectedN',v);
 const results=useMemo(()=>optimize(a),[computeKey]);
 const manual=useMemo(()=>validate(a).length?null:simulate({P:Math.max(a.pMin,Math.min(a.pMax,a.manualP)),Tin:Math.max(a.tMin,Math.min(a.tMax,a.manualT)),N:Math.max(1,Math.min(a.maxBeds,Math.round(a.manualN))),slope:a.manualSlope,cut:a.manualCut},a,true,.0005),[computeKey,a.manualP,a.manualT,a.manualN,a.manualSlope,a.manualCut]);
 const reference=useMemo(()=>validate(a).length?null:simulate(REPORT_REFERENCE,a,true,.0005),[computeKey]);
 const chosen=results.winners?.find(w=>w.N===selectedN)||results.best,r=mode==='manual'?manual:mode==='report'?reference:chosen;
 const reset=()=>{setAssumptions({...defaults});};
 const errors=results.errors||[],active=tabs.some(t=>t.id===activeTabId)?activeTabId:'thermo';
 return <article className="nh-app"><ExportPanel/><div className="nh-scope"><div><span className="nh-badge">Étude exploratoire · non calibrée</span><span>Exigence unique : <b>100 000 t NH₃/an</b></span></div><span>N₂ + 3 H₂ ⇌ 2 NH₃</span></div>
  <div className="nh-toolbar"><SegmentedControl options={[{value:'report',label:'Point du rapport'},{value:'optimum',label:'Candidat économique'},{value:'manual',label:'Exploration manuelle'}]} value={mode} onChange={setMode}/><span className="nh-toolbar-note">{mode==='report'?'Réglage du rapport ; bilans et coûts recalculés aux hypothèses actives.':mode==='optimum'?'Nouvelle recherche aux hypothèses actives.':'Faire varier les paramètres pour observer les trajectoires.'}</span><button className="nh-btn" onClick={reset}>Réinitialiser</button></div>
  {mode==='manual'&&<div className="nh-manual">{[['manualP','Pression',a.pMin,a.pMax,1,'bar'],['manualT','T° d’entrée',a.tMin,a.tMax,1,'°C'],['manualN','Nombre de lits',1,a.maxBeds,1,''],['manualSlope','Baisse de T° par lit',0,30,5,'°C'],['manualCut','Seuil r / pic',.1,.95,.05,'']].map(([k,label,min,max,step,unit])=><Slider key={k} label={label} min={min} max={max} step={step} value={Math.max(min,Math.min(max,a[k]))} onChange={v=>update(k,v)} formatValue={v=>fmt(v,k==='manualCut'?2:0)+' '+unit}/>)}</div>}
  {!!errors.length&&<div className="nh-error" role="alert"><b>Paramètres à corriger</b>{errors.map(e=><p key={e}>{e}</p>)}</div>}
  {r&&<><div className="nh-metrics" data-reviewed-rows><Mini label="Production imposée" value="100 000" unit="t/an" note={`${fmt(PRODUCTION/a.hours,2)} t/h · hypothèse ${fmt(a.hours,0)} h/an`}/><Mini label="Configuration sélectionnée" value={`${r.N} ${r.N===1?'lit':'lits'}`} unit={`${fmt(r.P,1)} bar`} note={`Entrées ${r.beds.map(b=>fmt(b.Tin,0)).join(' / ')} °C`}/><Mini label="Conversion par passage" value={pct(r.X,2)} note={`Recycle / frais : ${fmt(r.recycleRatio,2)}`}/><Mini label="Coût partiel · hypothèses" value={fmt(r.cost,2)} unit="MAD/t" note={`Recalculé à ${fmt(a.hours,0)} h/an · coûts hypothétiques`}/></div>{active==='thermo'&&<ThermoView r={r} a={a} update={update}/>} {active==='stages'&&<StagesView results={results} r={r} a={a} choose={n=>{setMode('optimum');setSelectedN(n);}}/>}{active==='loop'&&<LoopView r={r} a={a}/>} {active==='report'&&<ReportView r={r} a={a} Block={Block} DataGrid={DataGrid}/>}</>}
  {!r&&!errors.length&&<div className="nh-error" role="alert">Cette configuration ne permet pas une progression admissible dans tous les lits. Réduire le nombre de lits, revoir les températures ou élargir le domaine de recherche.</div>}
  {(active==='inputs'||!r)&&<InputsView a={a} update={update} results={results} r={r} reset={reset}/>}
  <footer className="nh-footer">Production fixe · propriétés NIST · calculs de scénario · {VERSION}<span>Les hypothèses et limites du modèle accompagnent les exports JSON.</span></footer></article>;
}
