import React from 'react';
import {Section} from '../../data-app-public.jsx';
import flowsheet from '../assets/report-flowsheet.png';
import {dimensionReactor} from './model.mjs';

const f=(n,d=2)=>n.toLocaleString('fr-FR',{minimumFractionDigits:d,maximumFractionDigits:d});
const historical=[
 [1,19.65,24.88,50.60,415.71],[2,27.80,34.68,64.22,356.22],
 [3,32.25,34.39,74.17,348.24],[4,34.65,35.17,83.69,352.59],
 [5,36.95,32.77,92.60,361.60],[6,38.20,35.55,102.17,371.89],
];
function ReactorSketch({d}){
 const gap=18,span=292-gap*Math.max(0,d.bedHeights.length-1);
 let y=106;
 const beds=d.bedHeights.map((height,index)=>{const h=height/d.totalBedHeight*span,bed={index,y,h};y+=h+gap;return bed;});
 return <div className="nh-reactor-sketch"><svg viewBox="0 0 540 550" role="img" aria-label={`Réacteur vertical de ${d.overallHeight.toFixed(2)} mètres de haut et ${d.vesselOD.toFixed(2)} mètres de diamètre extérieur, contenant ${d.bedHeights.length} lits annulaires.`}>
  <defs><marker id="nh-arrow" markerWidth="7" markerHeight="7" refX="3.5" refY="3.5" orient="auto-start-reverse"><path d="M0,0 L7,3.5 L0,7 z"/></marker></defs>
  <path className="nh-vessel" d="M150 72 Q270 10 390 72 L390 470 Q270 532 150 470 Z"/>
  <path className="nh-shell-line" d="M168 78 Q270 30 372 78 L372 464 Q270 512 168 464 Z"/>
  <rect className="nh-collector" x="244" y="91" width="52" height="370" rx="4"/>
  {beds.map(b=><g key={b.index}><rect className="nh-bed" x="185" y={b.y} width="170" height={b.h} rx="5"/><rect className="nh-collector-cut" x="244" y={b.y} width="52" height={b.h}/><text className="nh-sketch-label" x="198" y={b.y+b.h/2+4}>Lit {b.index+1} · {d.bedHeights[b.index].toFixed(2)} m</text></g>)}
  <line className="nh-dimension" x1="112" y1="43" x2="112" y2="504" markerStart="url(#nh-arrow)" markerEnd="url(#nh-arrow)"/><text className="nh-sketch-dimension" x="95" y="278" transform="rotate(-90 95 278)">H totale {d.overallHeight.toFixed(2)} m</text>
  <line className="nh-dimension" x1="150" y1="526" x2="390" y2="526" markerStart="url(#nh-arrow)" markerEnd="url(#nh-arrow)"/><text className="nh-sketch-dimension" x="270" y="545" textAnchor="middle">Ø ext. {d.vesselOD.toFixed(2)} m</text>
  <line className="nh-dimension nh-dimension-inner" x1="168" y1="487" x2="372" y2="487" markerStart="url(#nh-arrow)" markerEnd="url(#nh-arrow)"/><text className="nh-sketch-dimension" x="270" y="482" textAnchor="middle">Ø int. {d.vesselID.toFixed(2)} m</text>
  <text className="nh-sketch-small" x="270" y="66" textAnchor="middle">Fond ellipsoïdal 2:1 · profondeur {d.headDepth.toFixed(2)} m</text>
  <text className="nh-sketch-small" x="270" y="95" textAnchor="middle">Plénum supérieur {d.topPlenum.toFixed(2)} m</text>
  <text className="nh-sketch-small" x="270" y="474" textAnchor="middle">Plénum inférieur {d.bottomPlenum.toFixed(2)} m</text>
 </svg><div className="nh-sketch-key"><span><i className="nh-key-bed"/>Catalyseur</span><span><i className="nh-key-collector"/>Collecteur central</span><span><i className="nh-key-shell"/>Enveloppe froide</span></div></div>;
}
export default function ReportView({r,a,Block,DataGrid}){
 const load=r.freshMW+r.recycleMW+r.coolingMW;
 const d=dimensionReactor(r);
 const radialWidth=(d.basketOD-d.collectorOD)/2;
 const geometryRows=r.beds.map((b,index)=>[b.lit,f(b.mass/a.density),f(d.bedHeights[index]),f(d.basketOD),f(d.collectorOD),f(radialWidth),f(d.annulusArea),f(d.radialVelocities[index],3)]);
 return <>
  <div className="nh-callout"><b>Rapport de référence · 27 septembre 2026</b><p>Base retenue : 100 000 t NH₃/an, (365 − 21) × 24 = 8 256 h/an. Le rapport conserve le point à 3 lits, 122,5 bar et 32,25 % de conversion issu du screening à 8 000 h/an. Le mode « Point du rapport » applique ce réglage aux hypothèses actives ; « Candidat économique » relance la recherche.</p></div>
  <Section id="nh-reactor-title" title="Réacteur et charge catalytique" columns={2}>
   <Block id="nh-reactor-choice" title="Lits fixes adiabatiques, refroidissement indirect" rows={r.beds}><p>Chaque lit chauffe sous l’effet de la réaction. Un échangeur refroidit le gaz avant le lit suivant, sans mélange avec l’utilité. Le train complet n’est ni isotherme ni globalement adiabatique.</p><p>Architecture proposée : paniers à écoulement radial dans un corps sous pression. Le choix radial reste à confirmer avec le fournisseur ; aucune comparaison économique complète avec un réacteur isotherme n’est disponible.</p><p><b>Point affiché : {r.N} lits, {f(r.P,1)} bar, X = {f(r.X*100)} %.</b></p></Block>
   <Block id="nh-catalyst-choice" title="Fer promu · quantité de modèle" rows={r.beds}><p>Catalyseur proposé : fer promu. La cinétique de substitution n’est pas calibrée sur un grade commercial.</p><div className="nh-formula">W = F<sub>N₂,0</sub> ∫ dX/r<sub>N₂</sub><br/>V = W / ρ<sub>apparente</sub></div><p><b>{f(r.mass/1000)} t</b> équivalentes, soit <b>{f(r.volume)} m³</b> à {f(a.density,0)} kg/m³. À trajectoire et activité identiques, W varie avec le débit horaire.</p><p className="nh-note">La référence à 8 256 h/an donne environ 33,32 t et 15,15 m³. Charge fournisseur, granulométrie, désactivation et marge de fin de vie restent à confirmer.</p></Block>
  </Section>
  <Section id="nh-bed-design-title" title="Conditions et refroidissement du point affiché"><Block id="nh-bed-design" title="Détail des lits" rows={r.beds}><DataGrid head={['Lit','P entrée (bar abs)','T entrée (°C)','T sortie (°C)','X cumulé (%)','Catalyseur (t)','Volume (m³)','Échange suivant (MWth)']} rows={r.beds.map(b=>[b.lit,f(b.Pin,1),f(b.Tin,1),f(b.Tout,1),f(b.Xout*100),f(b.mass/1000),f(b.mass/a.density),f(b.coolMW)])}/></Block></Section>
  <Section id="nh-final-reactor-title" title="Réacteur final retenu pour l’avant-projet" columns={2}>
   <Block id="nh-reactor-drawing" title="Enveloppe verticale et paniers annulaires" rows={geometryRows.map(row=>({lit:row[0],hauteur_m:row[2],diametre_m:row[3]}))}><div className="nh-prelim-badge">Pré-dimensionnement mécanique · non certifié</div><ReactorSketch d={d}/><p className="nh-note">Le dessin est coté et proportionnel aux hauteurs de catalyseur ; les piquages, supports, soudures, isolation et détails internes ne sont pas à l’échelle.</p></Block>
   <Block id="nh-reactor-overall-dimensions" title="Dimensions totales et espaces internes" rows={[{vesselID:d.vesselID,vesselOD:d.vesselOD,tangentLength:d.tangentLength,overallHeight:d.overallHeight,thickness:d.nominalThickness}]}><DataGrid head={['Élément','Dimension','Base']} rows={[
    ['Corps — diamètre intérieur',f(d.vesselID),'m'],['Corps — diamètre extérieur',f(d.vesselOD),'m'],['Longueur entre tangentes',f(d.tangentLength),'m'],['Hauteur totale, fonds compris',f(d.overallHeight),'m'],['Hauteur totale de catalyseur',f(d.totalBedHeight),'m'],['Plénum supérieur / inférieur',`${f(d.topPlenum)} / ${f(d.bottomPlenum)}`,'m'],['Espace entre deux paniers',f(d.interbedSpace),'m'],['Fond ellipsoïdal 2:1 — profondeur',f(d.headDepth),'m'],['Épaisseur nominale proposée',f(d.nominalThickness,0),'mm'],['Jeu radial panier / enveloppe',f(d.radialClearance),'m par côté']
   ]}/><p className="nh-note">Pour le point de référence : enveloppe Ø intérieur 2,80 m, Ø extérieur 3,16 m et hauteur totale ≈ 7,57 m. La longueur réelle augmentera si le fournisseur ajoute des plateaux, accès ou collecteurs plus hauts.</p></Block>
  </Section>
  <Section id="nh-bed-geometry-title" title="Dimensions de chaque lit ou cellule"><Block id="nh-bed-geometry" title="Paniers catalytiques à écoulement radial vers le collecteur central" rows={geometryRows.map(row=>({lit:row[0],volume_m3:row[1],hauteur_m:row[2],diametre_exterieur_m:row[3],diametre_collecteur_m:row[4],epaisseur_radiale_m:row[5],section_m2:row[6],vitesse_m_s:row[7]}))}><DataGrid head={['Lit','Volume (m³)','Hauteur utile (m)','Ø panier ext. (m)','Ø collecteur (m)','Largeur radiale (m)','Section annulaire (m²)','Vitesse radiale* (m/s)']} rows={geometryRows}/><div className="nh-formula">A<sub>annulaire</sub> = π/4 (D² − d²) = {f(d.annulusArea,3)} m²<br/>H<sub>lit,i</sub> = V<sub>catalyseur,i</sub> / A<sub>annulaire</sub><br/>Largeur radiale = (D − d)/2 = {f(radialWidth)} m</div><p className="nh-note">*Vitesse de screening basée sur le débit réel à l’entrée, Z = {f(d.gasZ,2)}, soit {f(d.inletActualFlow,3)} m³/s. La perte de charge doit encore être calculée avec granulométrie, porosité et corrélation fournisseur.</p></Block></Section>
  <Section id="nh-mechanical-basis-title" title="Base mécanique de l’enveloppe" columns={2}>
   <Block id="nh-pressure-shell" title="Calcul préliminaire sous pression interne" rows={[{designPressure_bar:d.designPressure,wallTemperature_C:d.wallTemperature,stress_MPa:d.allowableStress,weldEfficiency:d.weldEfficiency,corrosion_mm:d.corrosionAllowance,shell_mm:d.shellCalculated,head_mm:d.headCalculated,selected_mm:d.nominalThickness}]}><DataGrid head={['Hypothèse','Valeur','Statut']} rows={[
    ['Pression de calcul',`${f(d.designPressure,0)} bar abs`,'max(150 bar ; 1,10 × P arrondi)'],['Température métal enveloppe',`${f(d.wallTemperature,0)} °C`,'Hypothèse paroi froide isolée'],['Contrainte admissible S',`${f(d.allowableStress,0)} MPa`,'Valeur provisoire à remplacer'],['Coefficient de soudure E',f(d.weldEfficiency,2),'Hypothèse contrôle complet'],['Surépaisseur corrosion c',`${f(d.corrosionAllowance,0)} mm`,'Hypothèse'],['Paroi cylindrique calculée',`${f(d.shellCalculated,1)} mm`,'Screening'],['Fond 2:1 calculé',`${f(d.headCalculated,1)} mm`,'Screening'],['Épaisseur nominale retenue',`${f(d.nominalThickness,0)} mm`,'Arrondi + marge préliminaire 8 %']
   ]}/><div className="nh-formula">t<sub>corps</sub> = P·R / (S·E − 0,6P) + c<br/>t<sub>fond 2:1</sub> = P·D / (2S·E − 0,2P) + c</div><p className="nh-note">Le corps est supposé « cold wall » avec isolation interne et thermocouples de peau. La température gaz maximale du modèle n’est pas la température de calcul du métal.</p></Block>
   <Block id="nh-material-and-code" title="Matériau, code et limites de validation" rows={[{architecture:'cold-wall',material:'famille 2¼Cr-1Mo, candidat',code:'ASME BPVC VIII-1',hydrogen:'API RP 941'}]}><p><b>Candidat :</b> acier de la famille 2¼Cr–1Mo pour service hydrogène chaud, à confirmer avec les courbes de Nelson, le mode de fabrication et les tables de contraintes admissibles.</p><p><b>Construction :</b> calcul détaillé selon ASME BPVC Section VIII Division 1, avec vérification des ouvertures, charges externes, fatigue, supports, essais, soudage et contrôles.</p><p><b>Pour rendre ces dimensions constructibles :</b> le fournisseur doit valider les propriétés réelles du gaz, la perte de charge, la distribution radiale, le grade matière, la température métal, les tolérances, les buses, la dilatation et les transitoires.</p><div className="nh-source-links"><a href="https://www.asme.org/codes-standards/find-codes-standards/bpvc-viii-1-bpvc-section-viii-rules-construction-pressure-vessels-division-1" target="_blank" rel="noreferrer">ASME BPVC VIII-1 ↗</a><a href="https://www.api.org/products-and-services/standards/industry-alert" target="_blank" rel="noreferrer">API RP 941 · service H₂ ↗</a></div></Block>
  </Section>
  <Section id="nh-cooling-choice-title" title="Pourquoi conserver le refroidissement indirect"><Block id="nh-quench-comparison" title="Choix retenu face au quench" rows={[{critere:'Température inter-lit',indirect:'échangeur et bypass',quench:'injection de gaz froid'},{critere:'Récupération de chaleur',indirect:r.qInterMW,quench:'niveau thermique abaissé'},{critere:'Débit traversant les lits',indirect:'pas de gaz ajouté',quench:'augmente après chaque injection'}]}><DataGrid head={['Critère','Refroidissement indirect retenu','Réacteur quench']} rows={[
   ['Réglage des entrées de lits','Échangeur + bypass chaud, réglage indépendant','Injection de gaz froid ; dépend du débit et de sa composition'],['Débit dans les lits','Aucun gaz ajouté entre les lits','Débit croissant après chaque quench'],['Récupération énergétique',`${f(r.qInterMW,2)} MWth inter-lits disponibles`,'Une partie du niveau thermique est diluée'],['Conséquence procédé','Stœchiométrie inchangée dans le train','Recycle, compresseur et distribution à réoptimiser'],['Avantage du quench','—','Moins d’échangeurs externes et réponse rapide']
  ]}/><p>Le quench reste techniquement possible. Il n’a pas été retenu parce que ce projet cherche simultanément le contrôle de température et la valorisation de l’exothermicité ; le refroidissement indirect conserve un flux chaud séparé et ne rajoute pas de débit au lit suivant.</p></Block></Section>
  <Section id="nh-control-title" title="Instrumentation et correction de température"><Block id="nh-instrumented-flowsheet" title="Schéma de principe du rapport · configuration à trois lits" rows={[
   {boucle:'Température',mesure:'TT / TI',regulateur:'TIC',action:'Bypass froid du préchauffeur ou bypass chaud des échangeurs inter-lits'},
   {boucle:'Alimentation',mesure:'FT',regulateur:'FIC',action:'Débit frais en maintenant le rapport H₂/N₂ de 3:1'},
   {boucle:'Protection thermique',mesure:'TSHH indépendant',regulateur:'SIS',action:'Arrêt / mise en sécurité à définir par HAZOP'},
  ]}><img src={flowsheet} alt="Boucle de synthèse trois lits avec échangeurs, mesures TI et TT, régulateurs TIC, vannes de bypass, récupération de chaleur, séparation, purge et recycle." style={{display:'block',width:'100%',height:'auto'}}/><p className="nh-note">Schéma du rapport pour trois lits ; il ne se redessine pas lorsque le nombre de lits exploré change. Document conceptuel, pas un P&ID d’exécution.</p><DataGrid head={['Fonction','Mesure / régulation','Action']} rows={[
   ['Entrée du premier lit','TT/TI ; TIC-101 ; préchauffeur E-100','Si la température monte, ouvrir le bypass froid autour de E-100. H-100 assure le chauffage de démarrage.'],
   ['Entrée des lits 2 et 3','TIC-102/TV-102 ; TIC-103/TV-103','Si la température monte, fermer le bypass chaud autour de E-101/E-102.'],
   ['Sorties des lits','TI-111 à TI-113','Indication, alarmes et suivi des gradients et points chauds.'],
   ['Alimentation','FT/FIC ; rapport H₂/N₂','Régler le débit frais en maintenant 3 mol H₂ / mol N₂.'],
   ['Séparateur et pression','PT/PIC ; LT/LIC','Contrôler la pression et la sortie NH₃ liquide ; protéger le compresseur contre le pompage.'],
   ['Sécurité indépendante','TSHH ; soupapes ; détection H₂/NH₃','Mise en sécurité et dépressurisation selon étude HAZOP/SIL ; seuils et positions de panne à valider.'],
  ]}/></Block></Section>
  <Section id="nh-report-energy-title" title="Valorisation de l’exothermicité"><Block id="nh-report-energy" title="Couverture des charges de synthèse" rows={[{generation_MWe:r.grossMW,charges_MWe:load,couverture_pct:100*r.grossMW/load}]}><div className="nh-formula">Q<sub>chimique</sub> × η<sub>récupération</sub> × η<sub>électrique</sub> = P<sub>génération</sub><br/>{f(r.rxnMW,3)} MWth × {f(a.recovery*100,0)} % × {f(a.electricEta*100,0)} % = {f(r.grossMW,3)} MWe</div><p>Couverture calculée : <b>{f(100*r.grossMW/load,1)} %</b> de {f(load,3)} MWe de charges ; import net : <b>{f(r.netMW,3)} MWe</b>. La chaleur peut produire de la vapeur pour une turbine et un alternateur. Ce potentiel ne démontre pas l’autonomie de l’unité ; le démarrage exige une énergie externe.</p><p className="nh-note">Amont H₂/N₂ exclu. Le réseau vapeur et la turbine restent à dimensionner. Le bilan inter-lits n’est pas ajouté une seconde fois à la chaleur chimique.</p></Block></Section>
  <Section id="nh-history-title" title="Origine du choix de trois lits"><Block id="nh-historical-comparison" title="Screening historique · 8 000 h/an, conservé dans le rapport" rows={historical.map(([lits,conversion_pct,catalyseur_t,CAPEX_MMAD,cout_MAD_t])=>({lits,conversion_pct,catalyseur_t,CAPEX_MMAD,cout_MAD_t}))}><DataGrid head={['Lits','X (%)','Catalyseur (t)','CAPEX (MMAD)','Coût partiel (MAD/t)']} rows={historical.map(row=>row.map((v,i)=>i===0?v:f(v)))}/><p>Le troisième lit économisait environ 0,80 MMAD/an par rapport à deux lits ; le quatrième ajoutait 0,44 MMAD/an. Les valeurs de ce tableau sont historiques. Les coûts du bandeau et de l’onglet optimisation sont recalculés aux hypothèses actives, dont {f(a.hours,0)} h/an.</p><p className="nh-note">Corrections arithmétiques par rapport au PDF : à 8 256 h/an et au point de référence, Q inter-lits ≈ 8,819 MWth, Q chimique ≈ 9,068 MWth et couverture électrique ≈ 30,7 %. Les anciennes valeurs 9,10 / 9,36 MW et 30,2 % ne sont pas reprises.</p></Block></Section>
 </>;
}
